# include<iostream>
using namespace std;
main()
{
 int num1;
 int num2;
 int num3;
 int num4;
 int num5;
 int num6;
 int num7;
 int num8;
 int num9;
 int num10;
 int num11;
 int num12;
 int num13;
 int num14;
 int num15;
 int add;
 int mul;
 int sub;
 int result;
 int totalresult;
 cout<<"entre first number...";
 cin>>num1; 
cout<<"entre second number...";
 cin>>num2;
  cout<<"entre third number...";
 cin>>num3; 
cout<<"entre fourth number...";
 cin>>num4;
  cout<<"entre fifthnumber...";
 cin>>num5; 
cout<<"entre sixth number...";
 cin>>num6;
  cout<<"entre seventh number...";
 cin>>num7; 
cout<<"entre eighth number...";
 cin>>num8;
  cout<<"entre ninth number...";
 cin>>num9; 
cout<<"entre tenth number...";
 cin>>num10;
  cout<<"entre elventh number...";
 cin>>num11; 
cout<<"entre tweleth number...";
 cin>>num12;
  cout<<"entre thirteenth number...";
 cin>>num13; 
cout<<"entre fourteenth number...";
 cin>>num14;
  cout<<"entre fifteenth number...";
 cin>>num15; 
 add=num1+num2+num3+num4+num5;
 mul=num6*num7*num8*num9*num10;
 sub=num11-num12-num13-num14-num15;
 result=add+mul;
 totalresult=result-sub;
 cout<<"total result is ...."<<totalresult;
}